name=ESP32_ST7789_Fast
version=1.0.0
author=Awulokune
maintainer=Awulokune
sentence=Fast ST7789 SPI display library for ESP32.
paragraph=Fast RGB565 graphics library for ST7789 displays using ESP32 SPI.
category=Display
url=https://github.com/Awulokune/ESP32_ST7789_Fast
architectures=esp32
depends=Adafruit GFX Library